# Generated by Django 3.2.6 on 2022-08-05 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0011_alter_perguntasanamnese_campo_anamnese_correspondente'),
        ('users', '0005_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anamnese',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='id_usuario', to='anamnese.anamnese', verbose_name='Anamnese'),
        ),
    ]
