# Generated by Django 3.2.6 on 2022-08-05 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0012_alter_perguntasanamnese_campo_anamnese_correspondente'),
        ('users', '0006_user_anamnese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='anamnese',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='id_usuario', to='anamnese.anamnese', verbose_name='Anamnese'),
        ),
    ]
