# Generated by Django 3.2.6 on 2022-08-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_anamnese'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='anamnese',
        ),
    ]
