# Generated by Django 3.2.6 on 2022-10-12 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_anamnese'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationForm',
        ),
    ]
