version: "3"
services:
  frontend :
    container_name: "virada_saude_frontend"
    build: ./frontend
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/ecr-app-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/home/ViradaSaude
    #command: "quasar build -m pwa"
    environment:
      - CHOKIDAR_USEPOLLING=true #variavel para permitir o hot-reloading
    depends_on:
      - api
  api:
    build: ./api
    container_name: "virada_saude_api"
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/ecr-app-api
    volumes:
      - ./api:/usr/src/app
      - ./api/mysqld:/var/run/mysqld
    ports:
      - 8000:8000
    environment:
      ENV: "development"
      PORT: 8000
    depends_on:
      - db

  db:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/ecr-app-db
    container_name: "virada_saude_db"
    command: "--default-authentication-plugin=mysql_native_password" #chmod -R 777 mysqld && 
    # restart: always
    ports:
      - 5500:3306 # alterando porta para facilitar conexao
    volumes:
      - ./docker/db/mysqldata:/var/lib/mysql
      - ./api/mysqld:/var/run/mysqld

