version: "3"
services:
  api:
    build: ./api
    container_name: "virada_saude_api"
    volumes:
      - ./api:/usr/src/app
      - ./api/mysqld:/var/run/mysqld
    ports:
      - 8000:8000
    environment:
      ENV: "development"
      PORT: 8000
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: "virada_saude_db"
    command: "--default-authentication-plugin=mysql_native_password" #chmod -R 777 mysqld && 
    # restart: always
    ports:
      - 5500:3306 # alterando porta para facilitar conexao
    volumes:
      - ./docker/db/mysqldata:/var/lib/mysql
      - ./api/mysqld:/var/run/mysqld

