# Generated by Django 3.2.6 on 2022-11-07 15:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id_dia_semana', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data_criacao')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='data_modificacao')),
            ],
            options={
                'verbose_name': 'Dia da Semana',
                'verbose_name_plural': 'Dias da Semana',
            },
        ),
        migrations.CreateModel(
            name='TempoDisponivel',
            fields=[
                ('id_tempo_disponivel', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_disponivel', models.IntegerField(null=True, verbose_name='periodo_disponivel')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data_criacao')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='data_modificacao')),
                ('id_dia_semana', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TempoDisponivel.diasemana')),
            ],
            options={
                'verbose_name': 'Tempo Disponível',
                'verbose_name_plural': 'Tempos Disponíveis',
            },
        ),
    ]
