# Generated by Django 3.2.6 on 2022-08-06 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id_dia_semana', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data_criacao')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='data_modificacao')),
            ],
            options={
                'verbose_name': 'Dia da Semana',
                'verbose_name_plural': 'Dias da Semana',
            },
        ),
        migrations.CreateModel(
            name='TempoDisponivel',
            fields=[
                ('id_tempo_disponivel', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField(verbose_name='hora_inicio')),
                ('hora_fim', models.TimeField(verbose_name='hora_fim')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data_criacao')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='data_modificacao')),
                ('id_dia_semana', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TempoDisponivel.diasemana')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tempo Disponível',
                'verbose_name_plural': 'Tempos Disponíveis',
            },
        ),
    ]
