# Generated by Django 3.2.6 on 2022-11-07 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TempoDisponivel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempodisponivel',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
