# Generated by Django 3.2.6 on 2022-08-09 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TempoDisponivel', '0002_alter_tempodisponivel_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempodisponivel',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
