# Generated by Django 3.2.6 on 2022-08-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TempoDisponivel', '0003_alter_tempodisponivel_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempodisponivel',
            name='hora_fim',
        ),
        migrations.RemoveField(
            model_name='tempodisponivel',
            name='hora_inicio',
        ),
    ]
