# Generated by Django 3.2.6 on 2022-08-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TempoDisponivel', '0004_auto_20220811_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempodisponivel',
            name='periodo_disponivel',
            field=models.IntegerField(null=True, verbose_name='periodo_disponivel'),
        ),
    ]
