# Generated by Django 3.2.6 on 2022-11-07 15:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id_feedback', models.AutoField(primary_key=True, serialize=False)),
                ('data_realizacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Realização')),
                ('clima', models.CharField(blank=True, max_length=150, null=True, verbose_name='Clima')),
                ('tempoPreSetadoUsuario', models.IntegerField(default=0, verbose_name='Tempo Pre Setado (em minutos)')),
                ('tempoTreinoRealizado', models.IntegerField(default=0, verbose_name='Tempo Realizado (em minutos)')),
            ],
        ),
        migrations.CreateModel(
            name='OpcaoRespostaFeedback',
            fields=[
                ('id_opcao_resposta_feedback', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=150, verbose_name='texto')),
            ],
        ),
        migrations.CreateModel(
            name='PerguntaFeedback',
            fields=[
                ('id_pergunta_feedback', models.AutoField(primary_key=True, serialize=False)),
                ('texto_pergunta', models.CharField(max_length=150, verbose_name='texto')),
                ('depende_de', models.ForeignKey(blank=True, db_column='depende_de', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='depende_de', to='feedback.opcaorespostafeedback')),
            ],
            options={
                'verbose_name': 'Pergunta do Feedback',
                'verbose_name_plural': 'Perguntas do Feedback',
            },
        ),
        migrations.CreateModel(
            name='ResultadoFeedback',
            fields=[
                ('id_resultado_feedback', models.AutoField(primary_key=True, serialize=False)),
                ('id_feedback', models.ForeignKey(blank=True, db_column='feedback', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultado_feedback', to='feedback.feedback', verbose_name='Id Feedback')),
                ('id_opcao_resposta_feedback', models.ForeignKey(blank=True, db_column='opcao_resposta_feedback', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opcao_resposta_feedback', to='feedback.opcaorespostafeedback', verbose_name='Opção Resposta')),
                ('id_pergunta_feedback', models.ForeignKey(blank=True, db_column='pergunta_feedback', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pergunta_feedback', to='feedback.perguntafeedback', verbose_name='Pergunta')),
            ],
        ),
        migrations.AddField(
            model_name='opcaorespostafeedback',
            name='id_pergunta_feedback',
            field=models.ForeignKey(blank=True, db_column='id_pergunta_feedback', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='opcoes', to='feedback.perguntafeedback'),
        ),
    ]
