# Generated by Django 3.2.6 on 2022-09-29 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcaoRespostaFeedback',
            fields=[
                ('id_opcao_resposta_feedback', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=150, verbose_name='texto')),
            ],
        ),
        migrations.CreateModel(
            name='PerguntaFeedback',
            fields=[
                ('id_pergunta_feedback', models.AutoField(primary_key=True, serialize=False)),
                ('texto_pergunta', models.CharField(max_length=150, verbose_name='texto')),
                ('depende_de', models.ForeignKey(blank=True, db_column='depende_de', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='depende_de', to='feedback.opcaorespostafeedback')),
            ],
            options={
                'verbose_name': 'Pergunta do Feedback',
                'verbose_name_plural': 'Perguntas do Feedback',
            },
        ),
        migrations.AddField(
            model_name='opcaorespostafeedback',
            name='id_pergunta_feedback',
            field=models.ForeignKey(blank=True, db_column='id_pergunta_feedback', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='feedback.perguntafeedback'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id_feedback', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
