# Generated by Django 3.2.6 on 2022-10-06 17:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0004_auto_20220921_1248'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='clima',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='clima'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='data_realizacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data_realizacao'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='treino',
            field=models.ForeignKey(blank=True, db_column='treino', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='treino', to='treino.treino'),
        ),
        migrations.AlterField(
            model_name='opcaorespostafeedback',
            name='id_pergunta_feedback',
            field=models.ForeignKey(blank=True, db_column='id_pergunta_feedback', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='opcoes', to='feedback.perguntafeedback'),
        ),
        migrations.CreateModel(
            name='ResultadoFeedback',
            fields=[
                ('id_resultado_feedback', models.AutoField(primary_key=True, serialize=False)),
                ('id_feedback', models.ForeignKey(blank=True, db_column='feedback', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='feedback', to='feedback.feedback')),
                ('id_opcao_resposta_feedback', models.ForeignKey(blank=True, db_column='opcao_resposta_feedback', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opcao_resposta_feedback', to='feedback.opcaorespostafeedback')),
                ('id_pergunta_feedback', models.ForeignKey(blank=True, db_column='pergunta_feedback', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pergunta_feedback', to='feedback.perguntafeedback')),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='resultado',
            field=models.ForeignKey(blank=True, db_column='resultado', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='resultado_feedback', to='feedback.resultadofeedback'),
        ),
    ]
