# Generated by Django 3.2.6 on 2022-10-06 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20221006_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='resultado',
        ),
        migrations.AlterField(
            model_name='resultadofeedback',
            name='id_feedback',
            field=models.ForeignKey(blank=True, db_column='feedback', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='resultado_feedback', to='feedback.feedback', verbose_name='Id Feedback'),
        ),
    ]
