# Generated by Django 3.2.6 on 2022-10-06 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20221006_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadofeedback',
            name='id_feedback',
            field=models.ForeignKey(blank=True, db_column='feedback', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultado_feedback', to='feedback.feedback', verbose_name='Id Feedback'),
        ),
    ]
