# Generated by Django 3.2.6 on 2022-10-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_resultadofeedback_id_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='tempoPreSetadoUsuario',
            field=models.IntegerField(default=0, verbose_name='Tempo Pre Setado (em minutos)'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='tempoTreinoRealizado',
            field=models.IntegerField(default=0, verbose_name='Tempo Realizado (em minutos)'),
        ),
    ]
