# Generated by Django 3.2.6 on 2022-11-07 15:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpcaoRespostaAnamnese',
            fields=[
                ('id_opcao_resposta_anamnese', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=150, verbose_name='texto')),
            ],
        ),
        migrations.CreateModel(
            name='PerguntasAnamnese',
            fields=[
                ('id_pergunta_anamnese', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=150, verbose_name='texto')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('select', 'Select'), ('multiselect', 'Multiselect'), ('numerico', 'Numérico')], max_length=150, verbose_name='tipo')),
                ('campo_anamnese_correspondente', models.CharField(choices=[('atividade_preferida_id', 'atividade_preferida_id'), ('condicao_fisica_atual', 'condicao_fisica_atual'), ('competitividade', 'competitividade'), ('diabetes', 'diabetes'), ('data_criacao', 'data_criacao'), ('usuario', 'usuario'), ('pressao_arterial', 'pressao_arterial'), ('atividade_fisica', 'atividade_fisica'), ('dieta_id', 'dieta_id'), ('peso_id', 'peso_id'), ('id_anamnese', 'id_anamnese'), ('atividade_fisica_id', 'atividade_fisica_id'), ('altura_id', 'altura_id'), ('atividade_preferida', 'atividade_preferida'), ('pressao_arterial_id', 'pressao_arterial_id'), ('pratica_corrida_id', 'pratica_corrida_id'), ('dieta', 'dieta'), ('aptidao_fisica_atual_id', 'aptidao_fisica_atual_id'), ('dor_muscular_id', 'dor_muscular_id'), ('tem_lesao_id', 'tem_lesao_id'), ('problema_coronariano', 'problema_coronariano'), ('dor_muscular', 'dor_muscular'), ('competitividade_id', 'competitividade_id'), ('diabetes_id', 'diabetes_id'), ('condicao_fisica_atual_id', 'condicao_fisica_atual_id'), ('problema_coronariano_id', 'problema_coronariano_id'), ('pratica_corrida', 'pratica_corrida'), ('tem_lesao', 'tem_lesao'), ('pratica_exercicio_academia', 'pratica_exercicio_academia'), ('altura', 'altura'), ('aptidao_fisica_atual', 'aptidao_fisica_atual'), ('data_modificacao', 'data_modificacao'), ('pratica_exercicio_academia_id', 'pratica_exercicio_academia_id'), ('usuario_id', 'usuario_id'), ('peso', 'peso')], max_length=100, null=True, unique=True, verbose_name='campo_anamnese_correspondente')),
                ('depende_de', models.ForeignKey(blank=True, db_column='depende_de', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='depende_de', to='anamnese.opcaorespostaanamnese')),
            ],
            options={
                'verbose_name': 'Pergunta da Anamnese',
                'verbose_name_plural': 'Perguntas da Anamnese',
            },
        ),
        migrations.AddField(
            model_name='opcaorespostaanamnese',
            name='id_pergunta_anamnese',
            field=models.ForeignKey(blank=True, db_column='id_pergunta_anamnese', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='anamnese.perguntasanamnese'),
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id_anamnese', models.AutoField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data_criacao')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='data_modificacao')),
                ('altura', models.ForeignKey(blank=True, db_column='altura', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='altura', to='anamnese.opcaorespostaanamnese')),
                ('aptidao_fisica_atual', models.ForeignKey(blank=True, db_column='aptidao_fisica_atual', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='aptidao_fisica_atual', to='anamnese.opcaorespostaanamnese')),
                ('atividade_fisica', models.ForeignKey(blank=True, db_column='atividade_fisica', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='atividade_fisica', to='anamnese.opcaorespostaanamnese')),
                ('atividade_preferida', models.ForeignKey(blank=True, db_column='atividade_preferida', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='atividade_preferida', to='anamnese.opcaorespostaanamnese')),
                ('competitividade', models.ForeignKey(blank=True, db_column='competitividade', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='competitividade', to='anamnese.opcaorespostaanamnese')),
                ('condicao_fisica_atual', models.ForeignKey(blank=True, db_column='condicao_fisica_atual', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='condicao_fisica_atual', to='anamnese.opcaorespostaanamnese')),
                ('diabetes', models.ForeignKey(blank=True, db_column='diabetes', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='diabetes', to='anamnese.opcaorespostaanamnese')),
                ('dieta', models.ForeignKey(blank=True, db_column='dieta', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dieta', to='anamnese.opcaorespostaanamnese')),
                ('dor_muscular', models.ForeignKey(blank=True, db_column='dor_muscular', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dor_muscular', to='anamnese.opcaorespostaanamnese')),
                ('peso', models.ForeignKey(blank=True, db_column='peso', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='peso', to='anamnese.opcaorespostaanamnese')),
                ('pratica_corrida', models.ForeignKey(blank=True, db_column='pratica_corrida', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pratica_corrida', to='anamnese.opcaorespostaanamnese')),
                ('pratica_exercicio_academia', models.ForeignKey(blank=True, db_column='pratica_exercicio_academia', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pratica_exercicio_academia', to='anamnese.opcaorespostaanamnese')),
                ('pressao_arterial', models.ForeignKey(blank=True, db_column='pressao_arterial', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pressao_arterial', to='anamnese.opcaorespostaanamnese')),
                ('problema_coronariano', models.ForeignKey(blank=True, db_column='problema_coronariano', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='problema_coronariano', to='anamnese.opcaorespostaanamnese')),
                ('tem_lesao', models.ForeignKey(blank=True, db_column='tem_lesao', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tem_lesao', to='anamnese.opcaorespostaanamnese')),
            ],
            options={
                'verbose_name': 'Anamnese',
                'verbose_name_plural': 'Anamneses',
            },
        ),
    ]
