# Generated by Django 3.2.6 on 2022-08-04 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntasAnamnese',
            fields=[
                ('id_pergunta_anamnese', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=150, verbose_name='texto')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('select', 'Select'), ('multiselect', 'Multiselect'), ('numerico', 'Numérico')], max_length=150, verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'Pergunta da Anamnese',
                'verbose_name_plural': 'Perguntas da Anamnese',
            },
        ),
        migrations.CreateModel(
            name='OpcaoRespostaAnamnese',
            fields=[
                ('id_opcao_resposta_anamnese', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=150, verbose_name='texto')),
                ('id_pergunta_anamnese', models.ForeignKey(blank=True, db_column='id_pergunta_anamnese', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='anamnese.perguntasanamnese')),
            ],
        ),
    ]
