# Generated by Django 3.2.6 on 2022-11-07 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anamnese', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='usuario',
            field=models.OneToOneField(blank=True, db_column='usuario', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='anamnese', to=settings.AUTH_USER_MODEL),
        ),
    ]
