# Generated by Django 3.2.6 on 2022-05-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntasAnamnese',
            fields=[
                ('id_pergunta_anamnese', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=150, verbose_name='texto_pergunta')),
                ('tipo', models.CharField(max_length=150, verbose_name='texto_pergunta')),
                ('campo_anamnese_correspondente', models.CharField(max_length=100, verbose_name='campo_anamnese_correspondente')),
                ('depende_de', models.IntegerField(null=True, verbose_name='condicao_fisica')),
            ],
        ),
    ]
