# Generated by Django 3.2.6 on 2022-08-04 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntasanamnese',
            name='depende_de',
            field=models.ForeignKey(blank=True, db_column='depende_de', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='depende_de', to='anamnese.opcaorespostaanamnese'),
        ),
    ]
