# Generated by Django 3.2.6 on 2022-08-04 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0002_perguntasanamnese_depende_de'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id_anamnese', models.AutoField(primary_key=True, serialize=False)),
                ('atividade_fisica', models.IntegerField(verbose_name='atividade_fisica')),
                ('dieta', models.IntegerField(verbose_name='dieta')),
                ('pressao_arterial', models.CharField(max_length=10, verbose_name='pressao_arterial')),
                ('tem_lesao', models.IntegerField(verbose_name='tem_lesao')),
                ('dores_musculares', models.IntegerField(verbose_name='dores_musculares')),
                ('diabetes', models.IntegerField(verbose_name='diabetes')),
                ('problema_coronariano', models.IntegerField(verbose_name='problema_coronariano')),
                ('competitividade', models.IntegerField(verbose_name='competitividade')),
                ('condicao_fisica', models.IntegerField(verbose_name='condicao_fisica')),
                ('nivel_apitidao', models.IntegerField(verbose_name='nivel_apitidao')),
                ('tempo_disponivel', models.IntegerField(verbose_name='tempo_disponivel')),
                ('pratica_corrida', models.ForeignKey(blank=True, db_column='pratica_corrida', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pratica_corrida', to='anamnese.opcaorespostaanamnese')),
            ],
            options={
                'verbose_name': 'Anamnese',
                'verbose_name_plural': 'Anamneses',
            },
        ),
    ]
