# Generated by Django 3.2.6 on 2022-05-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0003_auto_20220517_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntasanamnese',
            name='campo_anamnese_correspondente',
            field=models.CharField(choices=[('problema_coronariano', 'problema_coronariano'), ('dieta', 'dieta'), ('pratica_corrida', 'pratica_corrida'), ('condicao_fisica', 'condicao_fisica'), ('tempo_disponivel', 'tempo_disponivel'), ('nivel_apitidao', 'nivel_apitidao'), ('pressao_arterial', 'pressao_arterial'), ('atividade_fisica', 'atividade_fisica'), ('id_anamnese', 'id_anamnese'), ('tem_lesao', 'tem_lesao'), ('competitividade', 'competitividade'), ('dores_musculares', 'dores_musculares'), ('diabetes', 'diabetes')], max_length=100, unique=True, verbose_name='campo_anamnese_correspondente'),
        ),
    ]
