# Generated by Django 3.2.6 on 2022-08-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0003_anamnese'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnese',
            name='atividade_fisica',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='competitividade',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='condicao_fisica',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='diabetes',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='dieta',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='dores_musculares',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='nivel_apitidao',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='pressao_arterial',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='problema_coronariano',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='tem_lesao',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='tempo_disponivel',
        ),
    ]
