# Generated by Django 3.2.6 on 2022-08-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0004_auto_20220804_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntasanamnese',
            name='campo_anamnese_correspondente',
            field=models.CharField(choices=[('pratica_corrida_id', 'pratica_corrida_id'), ('pratica_corrida', 'pratica_corrida'), ('id_anamnese', 'id_anamnese')], max_length=100, null=True, unique=True, verbose_name='campo_anamnese_correspondente'),
        ),
    ]
