# Generated by Django 3.2.6 on 2022-05-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0005_alter_perguntasanamnese_campo_anamnese_correspondente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntasanamnese',
            name='campo_anamnese_correspondente',
            field=models.CharField(choices=[('pressao_arterial', 'pressao_arterial'), ('diabetes', 'diabetes'), ('dores_musculares', 'dores_musculares'), ('tempo_disponivel', 'tempo_disponivel'), ('nivel_apitidao', 'nivel_apitidao'), ('id_anamnese', 'id_anamnese'), ('dieta', 'dieta'), ('condicao_fisica', 'condicao_fisica'), ('tem_lesao', 'tem_lesao'), ('competitividade', 'competitividade'), ('pratica_corrida', 'pratica_corrida'), ('problema_coronariano', 'problema_coronariano'), ('atividade_fisica', 'atividade_fisica')], max_length=100, unique=True, verbose_name='campo_anamnese_correspondente'),
        ),
    ]
