# Generated by Django 3.2.6 on 2022-05-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0006_alter_perguntasanamnese_campo_anamnese_correspondente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntasanamnese',
            name='campo_anamnese_correspondente',
            field=models.CharField(choices=[('nivel_apitidao', 'nivel_apitidao'), ('tempo_disponivel', 'tempo_disponivel'), ('dieta', 'dieta'), ('id_anamnese', 'id_anamnese'), ('pratica_corrida', 'pratica_corrida'), ('pressao_arterial', 'pressao_arterial'), ('tem_lesao', 'tem_lesao'), ('atividade_fisica', 'atividade_fisica'), ('diabetes', 'diabetes'), ('problema_coronariano', 'problema_coronariano'), ('competitividade', 'competitividade'), ('dores_musculares', 'dores_musculares'), ('condicao_fisica', 'condicao_fisica')], max_length=100, unique=True, verbose_name='campo_anamnese_correspondente'),
        ),
    ]
