# Generated by Django 3.2.6 on 2022-05-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0007_alter_perguntasanamnese_campo_anamnese_correspondente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntasanamnese',
            name='campo_anamnese_correspondente',
            field=models.CharField(choices=[('id_anamnese', 'id_anamnese'), ('atividade_fisica', 'atividade_fisica'), ('tem_lesao', 'tem_lesao'), ('diabetes', 'diabetes'), ('pratica_corrida', 'pratica_corrida'), ('condicao_fisica', 'condicao_fisica'), ('pressao_arterial', 'pressao_arterial'), ('problema_coronariano', 'problema_coronariano'), ('dores_musculares', 'dores_musculares'), ('nivel_apitidao', 'nivel_apitidao'), ('dieta', 'dieta'), ('tempo_disponivel', 'tempo_disponivel'), ('competitividade', 'competitividade')], max_length=100, unique=True, verbose_name='campo_anamnese_correspondente'),
        ),
    ]
