# Generated by Django 3.2.6 on 2022-08-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0008_auto_20220805_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntasanamnese',
            name='campo_anamnese_correspondente',
            field=models.CharField(choices=[('atividade_fisica', 'atividade_fisica'), ('usuario', 'usuario'), ('usuario_id', 'usuario_id'), ('pratica_corrida_id', 'pratica_corrida_id'), ('pratica_corrida', 'pratica_corrida'), ('atividade_fisica_id', 'atividade_fisica_id'), ('id_anamnese', 'id_anamnese')], max_length=100, null=True, unique=True, verbose_name='campo_anamnese_correspondente'),
        ),
    ]
