# Generated by Django 3.2.6 on 2022-05-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0009_alter_perguntasanamnese_campo_anamnese_correspondente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntasanamnese',
            name='campo_anamnese_correspondente',
            field=models.CharField(choices=[('pratica_corrida', 'pratica_corrida'), ('dores_musculares', 'dores_musculares'), ('tem_lesao', 'tem_lesao'), ('condicao_fisica', 'condicao_fisica'), ('atividade_fisica', 'atividade_fisica'), ('diabetes', 'diabetes'), ('pressao_arterial', 'pressao_arterial'), ('tempo_disponivel', 'tempo_disponivel'), ('competitividade', 'competitividade'), ('problema_coronariano', 'problema_coronariano'), ('dieta', 'dieta'), ('id_anamnese', 'id_anamnese'), ('nivel_apitidao', 'nivel_apitidao')], max_length=100, unique=True, verbose_name='campo_anamnese_correspondente'),
        ),
    ]
