# Generated by Django 3.2.6 on 2022-05-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0011_alter_perguntasanamnese_campo_anamnese_correspondente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntasanamnese',
            name='campo_anamnese_correspondente',
            field=models.CharField(choices=[('pressao_arterial', 'pressao_arterial'), ('condicao_fisica', 'condicao_fisica'), ('problema_coronariano', 'problema_coronariano'), ('nivel_apitidao', 'nivel_apitidao'), ('id_anamnese', 'id_anamnese'), ('dores_musculares', 'dores_musculares'), ('tempo_disponivel', 'tempo_disponivel'), ('atividade_fisica', 'atividade_fisica'), ('competitividade', 'competitividade'), ('dieta', 'dieta'), ('tem_lesao', 'tem_lesao'), ('pratica_corrida', 'pratica_corrida'), ('diabetes', 'diabetes')], max_length=100, unique=True, verbose_name='campo_anamnese_correspondente'),
        ),
    ]
