# Generated by Django 3.2.6 on 2022-07-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0012_alter_perguntasanamnese_campo_anamnese_correspondente'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcaoRespostaAnamnese',
            fields=[
                ('id_opcao_resposta_anamnese', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=150, verbose_name='texto')),
            ],
        ),
        migrations.AlterField(
            model_name='perguntasanamnese',
            name='campo_anamnese_correspondente',
            field=models.CharField(choices=[('pratica_corrida', 'pratica_corrida'), ('atividade_fisica', 'atividade_fisica'), ('competitividade', 'competitividade'), ('tempo_disponivel', 'tempo_disponivel'), ('problema_coronariano', 'problema_coronariano'), ('dieta', 'dieta'), ('nivel_apitidao', 'nivel_apitidao'), ('dores_musculares', 'dores_musculares'), ('tem_lesao', 'tem_lesao'), ('diabetes', 'diabetes'), ('pressao_arterial', 'pressao_arterial'), ('id_anamnese', 'id_anamnese'), ('condicao_fisica', 'condicao_fisica')], max_length=100, unique=True, verbose_name='campo_anamnese_correspondente'),
        ),
        migrations.AlterField(
            model_name='perguntasanamnese',
            name='depende_de',
            field=models.IntegerField(blank=True, null=True, verbose_name='depende_de'),
        ),
    ]
