# Generated by Django 3.2.6 on 2022-07-31 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0013_auto_20220731_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcaorespostaanamnese',
            name='id_pergunta_anamnese',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='anamnese.perguntasanamnese'),
        ),
        migrations.AlterField(
            model_name='perguntasanamnese',
            name='campo_anamnese_correspondente',
            field=models.CharField(choices=[('diabetes', 'diabetes'), ('dieta', 'dieta'), ('nivel_apitidao', 'nivel_apitidao'), ('tempo_disponivel', 'tempo_disponivel'), ('dores_musculares', 'dores_musculares'), ('tem_lesao', 'tem_lesao'), ('pressao_arterial', 'pressao_arterial'), ('competitividade', 'competitividade'), ('id_anamnese', 'id_anamnese'), ('atividade_fisica', 'atividade_fisica'), ('condicao_fisica', 'condicao_fisica'), ('pratica_corrida', 'pratica_corrida'), ('problema_coronariano', 'problema_coronariano')], max_length=100, unique=True, verbose_name='campo_anamnese_correspondente'),
        ),
    ]
