# Generated by Django 3.2.6 on 2022-07-31 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0014_auto_20220731_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcaorespostaanamnese',
            name='id_pergunta_anamnese',
            field=models.ForeignKey(blank=True, db_column='id_pergunta_anamnese', null=True, on_delete=django.db.models.deletion.RESTRICT, to='anamnese.perguntasanamnese'),
        ),
        migrations.AlterField(
            model_name='perguntasanamnese',
            name='campo_anamnese_correspondente',
            field=models.CharField(choices=[('problema_coronariano', 'problema_coronariano'), ('dieta', 'dieta'), ('atividade_fisica', 'atividade_fisica'), ('dores_musculares', 'dores_musculares'), ('nivel_apitidao', 'nivel_apitidao'), ('competitividade', 'competitividade'), ('diabetes', 'diabetes'), ('id_anamnese', 'id_anamnese'), ('pratica_corrida', 'pratica_corrida'), ('pressao_arterial', 'pressao_arterial'), ('condicao_fisica', 'condicao_fisica'), ('tem_lesao', 'tem_lesao'), ('tempo_disponivel', 'tempo_disponivel')], max_length=100, unique=True, verbose_name='campo_anamnese_correspondente'),
        ),
    ]
