# Generated by Django 3.2.6 on 2022-08-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0018_auto_20220805_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntasanamnese',
            name='campo_anamnese_correspondente',
            field=models.CharField(choices=[('usuario_id', 'usuario_id'), ('pratica_corrida_id', 'pratica_corrida_id'), ('atividade_fisica_id', 'atividade_fisica_id'), ('atividade_fisica', 'atividade_fisica'), ('data_modificacao', 'data_modificacao'), ('pratica_corrida', 'pratica_corrida'), ('data_criacao', 'data_criacao'), ('usuario', 'usuario'), ('id_anamnese', 'id_anamnese')], max_length=100, null=True, unique=True, verbose_name='campo_anamnese_correspondente'),
        ),
    ]
