# Generated by Django 3.2.6 on 2022-08-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0019_alter_perguntasanamnese_campo_anamnese_correspondente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntasanamnese',
            name='campo_anamnese_correspondente',
            field=models.CharField(choices=[('usuario', 'usuario'), ('pratica_corrida', 'pratica_corrida'), ('atividade_fisica', 'atividade_fisica'), ('data_modificacao', 'data_modificacao'), ('atividade_fisica_id', 'atividade_fisica_id'), ('data_criacao', 'data_criacao'), ('usuario_id', 'usuario_id'), ('id_anamnese', 'id_anamnese'), ('pratica_corrida_id', 'pratica_corrida_id')], max_length=100, null=True, unique=True, verbose_name='campo_anamnese_correspondente'),
        ),
    ]
