# Generated by Django 3.2.6 on 2022-08-06 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0020_alter_perguntasanamnese_campo_anamnese_correspondente'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='dieta',
            field=models.ForeignKey(blank=True, db_column='dieta', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dieta', to='anamnese.opcaorespostaanamnese'),
        ),
        migrations.AlterField(
            model_name='perguntasanamnese',
            name='campo_anamnese_correspondente',
            field=models.CharField(choices=[('pratica_corrida_id', 'pratica_corrida_id'), ('dieta_id', 'dieta_id'), ('usuario', 'usuario'), ('atividade_fisica', 'atividade_fisica'), ('pratica_corrida', 'pratica_corrida'), ('dieta', 'dieta'), ('data_criacao', 'data_criacao'), ('atividade_fisica_id', 'atividade_fisica_id'), ('usuario_id', 'usuario_id'), ('data_modificacao', 'data_modificacao'), ('id_anamnese', 'id_anamnese')], max_length=100, null=True, unique=True, verbose_name='campo_anamnese_correspondente'),
        ),
    ]
