# Generated by Django 3.2.6 on 2022-08-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0021_auto_20220806_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntasanamnese',
            name='campo_anamnese_correspondente',
            field=models.CharField(choices=[('data_criacao', 'data_criacao'), ('dieta_id', 'dieta_id'), ('pratica_corrida', 'pratica_corrida'), ('pratica_corrida_id', 'pratica_corrida_id'), ('atividade_fisica_id', 'atividade_fisica_id'), ('data_modificacao', 'data_modificacao'), ('atividade_fisica', 'atividade_fisica'), ('usuario', 'usuario'), ('usuario_id', 'usuario_id'), ('id_anamnese', 'id_anamnese'), ('dieta', 'dieta')], max_length=100, null=True, unique=True, verbose_name='campo_anamnese_correspondente'),
        ),
    ]
