# Generated by Django 3.2.6 on 2022-11-07 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0022_alter_perguntasanamnese_campo_anamnese_correspondente'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='pratica_exercicio_academia',
            field=models.ForeignKey(blank=True, db_column='pratica_exercicio_academia', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pratica_exercicio_academia', to='anamnese.opcaorespostaanamnese'),
        ),
        migrations.AlterField(
            model_name='perguntasanamnese',
            name='campo_anamnese_correspondente',
            field=models.CharField(choices=[('pratica_exercicio_academia', 'pratica_exercicio_academia'), ('data_modificacao', 'data_modificacao'), ('id_anamnese', 'id_anamnese'), ('dieta', 'dieta'), ('data_criacao', 'data_criacao'), ('pratica_exercicio_academia_id', 'pratica_exercicio_academia_id'), ('usuario', 'usuario'), ('pratica_corrida', 'pratica_corrida'), ('usuario_id', 'usuario_id'), ('atividade_fisica', 'atividade_fisica'), ('atividade_fisica_id', 'atividade_fisica_id'), ('dieta_id', 'dieta_id'), ('pratica_corrida_id', 'pratica_corrida_id')], max_length=100, null=True, unique=True, verbose_name='campo_anamnese_correspondente'),
        ),
    ]
