# Generated by Django 3.2.6 on 2022-11-07 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0023_auto_20221107_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='pressao_arterial',
            field=models.ForeignKey(blank=True, db_column='pressao_arterial', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pressao_arterial', to='anamnese.opcaorespostaanamnese'),
        ),
        migrations.AlterField(
            model_name='perguntasanamnese',
            name='campo_anamnese_correspondente',
            field=models.CharField(choices=[('id_anamnese', 'id_anamnese'), ('usuario', 'usuario'), ('atividade_fisica', 'atividade_fisica'), ('pressao_arterial_id', 'pressao_arterial_id'), ('atividade_fisica_id', 'atividade_fisica_id'), ('dieta_id', 'dieta_id'), ('pratica_exercicio_academia_id', 'pratica_exercicio_academia_id'), ('pressao_arterial', 'pressao_arterial'), ('data_modificacao', 'data_modificacao'), ('dieta', 'dieta'), ('usuario_id', 'usuario_id'), ('pratica_corrida', 'pratica_corrida'), ('data_criacao', 'data_criacao'), ('pratica_corrida_id', 'pratica_corrida_id'), ('pratica_exercicio_academia', 'pratica_exercicio_academia')], max_length=100, null=True, unique=True, verbose_name='campo_anamnese_correspondente'),
        ),
    ]
