# Generated by Django 3.2.6 on 2022-11-07 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0024_auto_20221107_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='dor_muscular',
            field=models.ForeignKey(blank=True, db_column='dor_muscular', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dor_muscular', to='anamnese.opcaorespostaanamnese'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='tem_lesao',
            field=models.ForeignKey(blank=True, db_column='tem_lesao', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tem_lesao', to='anamnese.opcaorespostaanamnese'),
        ),
        migrations.AlterField(
            model_name='perguntasanamnese',
            name='campo_anamnese_correspondente',
            field=models.CharField(choices=[('dieta', 'dieta'), ('atividade_fisica_id', 'atividade_fisica_id'), ('usuario', 'usuario'), ('usuario_id', 'usuario_id'), ('pratica_corrida', 'pratica_corrida'), ('pratica_corrida_id', 'pratica_corrida_id'), ('atividade_fisica', 'atividade_fisica'), ('tem_lesao', 'tem_lesao'), ('dieta_id', 'dieta_id'), ('tem_lesao_id', 'tem_lesao_id'), ('data_modificacao', 'data_modificacao'), ('id_anamnese', 'id_anamnese'), ('pratica_exercicio_academia', 'pratica_exercicio_academia'), ('pressao_arterial_id', 'pressao_arterial_id'), ('pratica_exercicio_academia_id', 'pratica_exercicio_academia_id'), ('data_criacao', 'data_criacao'), ('dor_muscular', 'dor_muscular'), ('dor_muscular_id', 'dor_muscular_id'), ('pressao_arterial', 'pressao_arterial')], max_length=100, null=True, unique=True, verbose_name='campo_anamnese_correspondente'),
        ),
    ]
