# Generated by Django 3.2.6 on 2022-11-07 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0025_auto_20221107_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='competitividade',
            field=models.ForeignKey(blank=True, db_column='competitividade', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='competitividade', to='anamnese.opcaorespostaanamnese'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='diabetes',
            field=models.ForeignKey(blank=True, db_column='diabetes', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='diabetes', to='anamnese.opcaorespostaanamnese'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='problema_coronariano',
            field=models.ForeignKey(blank=True, db_column='problema_coronariano', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='problema_coronariano', to='anamnese.opcaorespostaanamnese'),
        ),
        migrations.AlterField(
            model_name='perguntasanamnese',
            name='campo_anamnese_correspondente',
            field=models.CharField(choices=[('dor_muscular', 'dor_muscular'), ('competitividade', 'competitividade'), ('atividade_fisica_id', 'atividade_fisica_id'), ('pratica_corrida', 'pratica_corrida'), ('competitividade_id', 'competitividade_id'), ('data_criacao', 'data_criacao'), ('pratica_exercicio_academia_id', 'pratica_exercicio_academia_id'), ('dor_muscular_id', 'dor_muscular_id'), ('pratica_corrida_id', 'pratica_corrida_id'), ('pratica_exercicio_academia', 'pratica_exercicio_academia'), ('usuario', 'usuario'), ('tem_lesao_id', 'tem_lesao_id'), ('tem_lesao', 'tem_lesao'), ('diabetes_id', 'diabetes_id'), ('data_modificacao', 'data_modificacao'), ('pressao_arterial', 'pressao_arterial'), ('usuario_id', 'usuario_id'), ('problema_coronariano_id', 'problema_coronariano_id'), ('diabetes', 'diabetes'), ('pressao_arterial_id', 'pressao_arterial_id'), ('dieta', 'dieta'), ('problema_coronariano', 'problema_coronariano'), ('id_anamnese', 'id_anamnese'), ('atividade_fisica', 'atividade_fisica'), ('dieta_id', 'dieta_id')], max_length=100, null=True, unique=True, verbose_name='campo_anamnese_correspondente'),
        ),
    ]
