# Generated by Django 3.2.6 on 2022-11-07 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0026_auto_20221107_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='altura',
            field=models.ForeignKey(blank=True, db_column='altura', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='altura', to='anamnese.opcaorespostaanamnese'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='aptidao_fisica_atual',
            field=models.ForeignKey(blank=True, db_column='aptidao_fisica_atual', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='aptidao_fisica_atual', to='anamnese.opcaorespostaanamnese'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='atividade_preferida',
            field=models.ForeignKey(blank=True, db_column='atividade_preferida', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='atividade_preferida', to='anamnese.opcaorespostaanamnese'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='condicao_fisica_atual',
            field=models.ForeignKey(blank=True, db_column='condicao_fisica_atual', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='condicao_fisica_atual', to='anamnese.opcaorespostaanamnese'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='peso',
            field=models.ForeignKey(blank=True, db_column='peso', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='peso', to='anamnese.opcaorespostaanamnese'),
        ),
        migrations.AlterField(
            model_name='perguntasanamnese',
            name='campo_anamnese_correspondente',
            field=models.CharField(choices=[('pratica_corrida_id', 'pratica_corrida_id'), ('atividade_preferida', 'atividade_preferida'), ('peso', 'peso'), ('competitividade', 'competitividade'), ('tem_lesao_id', 'tem_lesao_id'), ('pratica_corrida', 'pratica_corrida'), ('atividade_fisica_id', 'atividade_fisica_id'), ('diabetes_id', 'diabetes_id'), ('altura', 'altura'), ('dor_muscular_id', 'dor_muscular_id'), ('condicao_fisica_atual', 'condicao_fisica_atual'), ('tem_lesao', 'tem_lesao'), ('usuario_id', 'usuario_id'), ('condicao_fisica_atual_id', 'condicao_fisica_atual_id'), ('dieta_id', 'dieta_id'), ('pressao_arterial_id', 'pressao_arterial_id'), ('problema_coronariano', 'problema_coronariano'), ('pratica_exercicio_academia_id', 'pratica_exercicio_academia_id'), ('diabetes', 'diabetes'), ('aptidao_fisica_atual', 'aptidao_fisica_atual'), ('pratica_exercicio_academia', 'pratica_exercicio_academia'), ('atividade_preferida_id', 'atividade_preferida_id'), ('peso_id', 'peso_id'), ('id_anamnese', 'id_anamnese'), ('aptidao_fisica_atual_id', 'aptidao_fisica_atual_id'), ('altura_id', 'altura_id'), ('atividade_fisica', 'atividade_fisica'), ('data_criacao', 'data_criacao'), ('competitividade_id', 'competitividade_id'), ('dieta', 'dieta'), ('usuario', 'usuario'), ('problema_coronariano_id', 'problema_coronariano_id'), ('data_modificacao', 'data_modificacao'), ('pressao_arterial', 'pressao_arterial'), ('dor_muscular', 'dor_muscular')], max_length=100, null=True, unique=True, verbose_name='campo_anamnese_correspondente'),
        ),
    ]
