# Generated by Django 3.2.6 on 2022-09-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id_treino', models.AutoField(primary_key=True, serialize=False)),
                ('intensidade', models.CharField(choices=[('leve', 'Leve'), ('medio', 'Médio'), ('pesado', 'Pesado')], max_length=150, verbose_name='intensidade')),
                ('tipo_treino', models.CharField(choices=[('caminhada', 'Caminhada'), ('joging', 'Joging'), ('corrida', 'Corrida')], max_length=150, verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'Treino',
                'verbose_name_plural': 'Treinos',
            },
        ),
    ]
