# Generated by Django 3.2.6 on 2022-09-21 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id_treino', models.AutoField(db_column='id_treino', primary_key=True, serialize=False)),
                ('data_execucao_prevista', models.DateTimeField(db_column='data_execucao_prevista', default=django.utils.timezone.now, verbose_name='Data da execução prevista')),
                ('data_execucao', models.DateTimeField(db_column='data_execucao', default=django.utils.timezone.now, verbose_name='Data da execução')),
                ('created', models.DateTimeField(auto_now=True, db_column='created', verbose_name='Criado')),
                ('modified', models.DateTimeField(db_column='modified', default=django.utils.timezone.now, verbose_name='Última modificação')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Treino',
                'verbose_name_plural': 'Treinos',
            },
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id_exercicio', models.AutoField(auto_created=True, db_column='id_exercicio', primary_key=True, serialize=False)),
                ('intensidade', models.CharField(choices=[('leve', 'Leve'), ('medio', 'Médio'), ('pesado', 'Pesado')], db_column='intensidade', max_length=150, verbose_name='Intensidade')),
                ('tipo_treino', models.CharField(choices=[('caminhada', 'Caminhada'), ('joging', 'Joging'), ('corrida', 'Corrida')], db_column='tipo_treino', max_length=150, verbose_name='Tipo de treino')),
                ('porcentagem_treino', models.IntegerField(db_column='porcentagem_treino', null=True, verbose_name='Porcentagem do treino completo')),
                ('treino', models.ForeignKey(blank=True, db_column='id_treino', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='treino.treino', verbose_name='Treino')),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
            },
        ),
    ]
