# Generated by Django 3.2.6 on 2022-09-20 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id_treino', models.AutoField(primary_key=True, serialize=False, verbose_name='id_treino')),
                ('data_execucao_prevista', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data_execucao_prevista')),
                ('data_execucao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data_execucao')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Treino',
                'verbose_name_plural': 'Treinos',
            },
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id_exercicio', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id_exercicio')),
                ('intensidade', models.CharField(choices=[('leve', 'Leve'), ('medio', 'Médio'), ('pesado', 'Pesado')], max_length=150, verbose_name='intensidade')),
                ('tipo_treino', models.CharField(choices=[('caminhada', 'Caminhada'), ('joging', 'Joging'), ('corrida', 'Corrida')], max_length=150, verbose_name='tipo')),
                ('porcentagem_treino', models.IntegerField(null=True, verbose_name='porcentagem_treino')),
                ('treino', models.ForeignKey(blank=True, db_column='treino', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='treino.treino')),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
            },
        ),
    ]
