# Generated by Django 3.2.6 on 2022-11-07 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treino', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='treino',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='usuario', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='treino',
            field=models.ForeignKey(blank=True, db_column='id_treino', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exercicio', to='treino.treino', verbose_name='Treino'),
        ),
    ]
