# Generated by Django 3.2.6 on 2022-09-21 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0003_alter_treino_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='data_execucao',
            field=models.DateField(db_column='data_execucao', default=django.utils.timezone.now, verbose_name='Data da execução'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='data_execucao_prevista',
            field=models.DateField(db_column='data_execucao_prevista', default=django.utils.timezone.now, verbose_name='Data da execução prevista'),
        ),
    ]
