# Generated by Django 3.2.6 on 2022-10-12 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0004_auto_20220921_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='data_execucao',
            field=models.DateField(db_column='data_execucao', default=django.utils.timezone.now, null=True, verbose_name='Data da execução'),
        ),
    ]
