# Generated by Django 3.2.6 on 2022-10-12 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0005_alter_treino_data_execucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='data_execucao',
            field=models.DateField(blank=True, db_column='data_execucao', default=django.utils.timezone.now, null=True, verbose_name='Data da execução'),
        ),
    ]
