# Generated by Django 3.2.6 on 2022-10-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0006_alter_treino_data_execucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='treino',
            name='cancelado',
            field=models.BooleanField(blank=True, db_column='cancelado', default=False, verbose_name='CFalseancelado'),
        ),
    ]
