# Generated by Django 3.2.6 on 2022-10-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0007_treino_cancelado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='cancelado',
            field=models.BooleanField(blank=True, db_column='cancelado', default=False, verbose_name='Cancelado'),
        ),
    ]
